
---
agetitle: "Global Access to Water and Sanitation"
output: 
  html_document:
    theme: lumen
    css: "../../../z-assemblers/assets/styles/content.css"
    df_print: paged
    mathjax: NULL
    self_contained: false
    lib_dir: "vendor"
---
```{r setup, include=FALSE}

knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
options(scipen=999)  # turn-off scientific notation like 1e+48

# Clear environment and memory
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memory and report the memory usage.

library(tidyverse)
library(ggiraph)

library(showtext)
## Loading Google fonts (https://fonts.google.com/)
font_add_google("Inconsolata", "inconsolata")
# turn on showtext
showtext_auto()

```


```{r load-data, echo=FALSE, message=FALSE, warning=FALSE}

df <- read.csv('./access-to-water-and-sanitation.csv', header = TRUE, stringsAsFactors = FALSE)

```

```{r method: position, echo=FALSE, message=FALSE, warning=FALSE}

filter_position <- function(df_position,row_var,column_var) {
  df_position[row_var,column_var]
}

# Call the function to filter the data set 
#filter_position(df,c(4,10,100:600), c(1,3:5))
filter_position(df,c(4,10,100,600), c(1,3,5))
```


